version: '3.3'

services:

  psymatch-backend:
    container_name: psymatch-backend
    build: ./
    ports:
      - "8080:8080"
    volumes:
      - ../../:/app
    depends_on:
      - psymatch-mongodb
    restart: always
    environment:
      - DB_HOST=psymatch-mongodb
      - DB_PORT=27017

  psymatch-mongodb:
    container_name: psymatch-mongodb
    image: mongo:3.6
    volumes:
      - ./data/db:/data/db
    ports:
      - "27017:27017"
    restart: always

