
server:
  port: 8080
  servlet:
    context-path: /api

spring:
  data:
    mongodb:
      host: ${DB_HOST:localhost}
      port: ${DB_PORT:27017}
      database: psymatch
      username: mongodb_admin
      password: MiVpp1g
      authentication-database: admin
#при пуше на git, убрать комментари с username,password, authentication-database
#и сменить порт на 27017


#logging:
#  file: logs/dev_psymatch_backend.log
##  pattern:
##    console: "%d %-5level %logger : %msg%n"
##    file: "%d %-5level [%thread] %logger : %msg%n"
#  level:
##    org.springframework.web: INFO
#    com.psycorp.controller: TRACE
##    org.hibernate: DEBUG