
server:
  port: 8080
  servlet:
    context-path: /api

spring:
  data:
    mongodb:
      host: ${DB_HOST:localhost}
      port: ${DB_PORT:27017}
      database: psymatch
      username: mongodb_admin
      password: MiVpp1g
      authentication-database: admin
#при пуше на git, убрать комментари с username,password, authentication-database
#и сменить порт на 27017
